### ISSUE TITLE
Checkbox component from @availity/form package expects string type for label prop, but should accept PropTypes.node

### ISSUE THREAD

**Issue by clintonlunn** [Availity/availity-react#1272]
### Current Behavior

When using the `Checkbox` component from the `@availity/form` package, we receive the following error message: 
![image](https://user-images.githubusercontent.com/24685932/236324299-c9fd4b00-3bc5-454a-a086-57ca3b8df938.png)
`Warning: Failed prop type: Invalid prop label of type object supplied to Checkbox, expected string.`

### Expected behavior

The `Checkbox` component should accept a `label` prop of any valid renderable content type, including strings, numbers, and React components.

### Reproducible example

Codesandbox: https://codesandbox.io/p/sandbox/sample-av-form-forked-4wd1vj

```jsx
<Form
  initialValues={initialValues}
  validationSchema={formSchema}
  onSubmit={(values) => console.log("values", values)}
>
  <CheckboxGroup name="checkbox1">
    <Checkbox
      id="checkbox1"
      groupName="checkbox1"
      label={<>content</>} // <-- this is breaking things
      value="yes"
    />
  </CheckboxGroup>
  <Button type="submit" color="primary">
    Submit
  </Button>
</Form>
```

### Suggested solution(s)

The `Checkbox` component should be updated to accept a label prop of type `PropTypes.node` instead of `PropTypes.string`. This will allow the label prop to accept any valid renderable content type.

Suggestion location to fix: https://github.com/Availity/availity-react/blob/464fb151ececc6a3c3485fd32f53e1ceb80f668e/packages/form/src/Checkbox.js#L72

### Your environment

```bash
➜  workspace git:(master) ✗ npx envinfo --npmPackages '@availity/*' --binaries


  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @availity/date: 3.4.4 => 3.4.4 
    @availity/form: 1.7.1 => 1.7.1 
    @availity/yup: 5.1.2 => 5.1.2 

```

**Comment by LauRoxx** [comment]
sounds good to me. out of curiosity, what are you trying to add to the label? just small text or other styling?

**Comment by clintonlunn** [comment]
> sounds good to me. out of curiosity, what are you trying to add to the label? just small text or other styling?

Thanks for the reply! I need to use it with a tooltip.

```jsx
const label = (
  <>
      The label that I want to use.
      <Tooltip
          id="tooltipId"
          label="This is a tooltip label that I want to use"
          placement="right"
      >
          <Icon
              id="tooltipIconId"
              name="help-circle"
          />
      </Tooltip>
  </>
)

<CheckboxGroup name="checkbox1">
    <Checkbox
      id="checkbox1"
      groupName="checkbox1"
      label={label} // <-- this is breaking things
      value="yes"
    />
</CheckboxGroup>
```

Also, I'd be happy to go make this change if agreed it's an issue.

**Comment by LauRoxx** [comment]
interesting. I thought the hover info pattern wasn't in use anymore (and used the info circle icon instead of the help). Unfortunately for this to be accessible it'd likely need to be setup in the label component similar to how the help topics are. It's been low on the feature list for a while to add a custom right content section so it's beside the label instead of within it, but should be easy enough.

**Comment by clintonlunn** [comment]
@LauRoxx a little bit confused. Are you saying the way that I am using breaks the accessibility here?

**Comment by LauRoxx** [comment]
From the looks of it yes. Not sure how a keyboard only user would be able to activate the hover info. Typically the icon would be made focusable so a keyboard user would be able to activate it, but we've been dinged before for having nested interactive content (since the label itself is clickable) but i wonder if that wouldn't apply here since it's just focus behavior and not selecting behavior? 
I'm also rusty on how tooltips are handled by the screenreader and if additional aria-describedby behavior is needed on your icon, but that's more of a how you decide to implement question and not related to the checkbox/label components.

**Comment by clintonlunn** [comment]
I need to test this with a screenreader, but when I tab to this using keyboard, the hover info visually displays. Also, I only posted an absolute minimum example, removing all of the aria-* attributes for clarity. Those are in my actual implementation

```jsx
<Checkbox
    id="checkboxId"
    groupName="checkboxgroupnameid"
    label={
        <>
            lorem ipsum this is a label
            <Tooltip
                id="tooltipId"
                label="default tooltip label"
                placement="right"
            >
                <Icon
                    role="link"
                    id="iconId"
                    name="help-circle"
                    tabIndex={0}
                    aria-hidden="false"
                    aria-label="example tooltip icon"
                />
            </Tooltip>
        </>
    }
    value="yes"
/>
```
