### ISSUE TITLE
AvDateRange Change Button Color when picker changes

### ISSUE THREAD

**Issue by adrian-santos** [Availity/availity-react#190]
Can the [Button Color](https://github.com/Availity/availity-react/blob/b9f54d419dd6a77a8b60cdde86a8efa0341aa531/packages/reactstrap-validation-date/AvDateRange.js#L392) change into Availity's Dark Blue Color when there's an input/change in [Date Range](https://github.com/Availity/availity-react/blob/master/packages/reactstrap-validation-date/AvDateRange.js#L431)?

**Comment by GoPro16** [comment]
Since this is a one off case we can create `buttonProps` to the components and then you can manually update the color on the [`onChange`](https://github.com/Availity/availity-react/blob/b9f54d419dd6a77a8b60cdde86a8efa0341aa531/packages/reactstrap-validation-date/AvDateRange.js#L330) callback.

Unless there is a strong enough justification to make this a global change for the `onChange` to trigger that the above is the correct case. Feel free to submit a PR

**Comment by adrian-santos** [comment]
Closing the issue. Will be using another UX pattern instead
