### ISSUE TITLE
Creatable support ??

### ISSUE THREAD

**Issue by AbderrahimRayes** [Availity/availity-react#25]
Hi do you support creatable select ? because i can't find a clue about creatable.

**Comment by robmcguinness** [comment]
sorry for late response. i'm not really following the question. what do you mean creatable select?

**Comment by GoPro16** [comment]
Found its part of the `react-select` package [here](https://react-select.com/creatable). This is definitely feasible since we are already including the component from the `react-select-async-pagination` which is forked so that we can get `Async` Selects. 

Right now there isn't an immediate need for this feature but I will keep this open in case someone else wants to take this on our it gains popularity.

**Comment by nylon22** [comment]
I have a use case for this. taking it
