### ISSUE TITLE
PageHeader Accessibility/UX

### ISSUE THREAD

**Issue by GoPro16** [Availity/availity-react#290]
For the current `@availity/page-header`, inside the `h1` tag we are displaying the appIcon, feedback and the appname. I am not sure on its usefulness from a UX/acccessiblity perspective as the heading tags should just contain text content about the page.

https://github.com/Availity/availity-react/blob/037d4d77a084bbb3991bd26220d938d80c5683fd/packages/page-header/PageHeader.js#L81-L106

If we were to change this the heading would only be used for identifying the `appName` so that we can also include maybe a sub section of the appName such as a `summary`.

I was noting this as I was trying to introduce the `@availity/page-header` component into the  gatsby docs. However, we also have a `summary` text that is rendered below the main heading but we are unable to do this with how the component is currently structured.

**Comment by jordan-a-young** [comment]
I have been meaning to open an issue with how the page-header displays the
title and its children. My team likes to put buttons in there which means I
can't use the appName prop for the title nor the Feedback button because of
the way children are handled. If I want to have other buttons I also have
to supply the Feedback button.

It's not so much an accessibility issue, but wanted to get it out there if
a redesign is in mind.

**Comment by GoPro16** [comment]
closed via #292
