### ISSUE TITLE
Update DateField and DateRangeField PropTypes

### ISSUE THREAD

**Issue by jordan-a-young** [Availity/availity-react#299]
Currently, the DateField and DateRangeField label prop only accepts a string. Can we have the label prop updated to accept a component as well?

For example, this would allow passing the `reactstrap` Label component.

**Comment by nylon22** [comment]
@jordan-a-young [DateField](https://github.com/Availity/availity-react/blob/master/packages/date/src/DateField.js#L9) and [DateRangeField](https://github.com/Availity/availity-react/blob/master/packages/date/src/DateRangeField.js#L9) already render a `reactstrap` `<Label />` when the `label` prop is provided. I don't see the value in allowing a `node` to be passed in instead. 

Please reopen if you think this is still an issue.

**Comment by jordan-a-young** [comment]
In our labels we like to add help icons the user can click on to get more
information. If there is another way to do this other than using the label
prop, I'm open to updating my code.

**Comment by GoPro16** [comment]
I think if we are going to add something like a help icon with popover text it should be the same across all our components. It should be rendered most likely next to the Field Label but not available possibly for the standard `Input` Field.

**Comment by jordan-a-young** [comment]
I have a `HelpIcon` component I can push up if that's the route we want to take. This change in prop-type is something we may want to add to the migration guide as people will start seeing warnings if they try to use the new `@availity/date` component compared to the old `@availity/reactstrap-validation-date`.

https://github.com/Availity/availity-react/blob/master/packages/reactstrap-validation-date/src/AvDateField.js#L12

**Comment by TheSharpieOne** [comment]
I feel like you shouldn't be restricting proptypes like that. `Label` accepts a node as its children, so anything being forwarded to Label should also allow a node.
Being consistent with a help icon and tooltip is a separate, more difficult issue. Even with `Label`'s proptype being a string, it doesn't enforce it; only giving a warning in development.
IMHO, proptypes should define the types which your component can handle, not desired types. If you expect a string so that you can access functions such as `.substr()` on it, then sure, restrict it to a string. But in this case, no such restrictions are needed, the components works with any value within the node proptype.

**Comment by GoPro16** [comment]
Yeah we ran into some `typescript` definition issues when we had the `label` restricted to a `string`. I think this was more so a developer error than it was restricting to just a string value which I take responsibility for that. 

I think moving fast is good but now we are taking time to double back and make sure all of these are up to date and sync up with the docs before adding newer updates/components.

**Comment by stevenviar** [comment]
closed with #306
