### ISSUE TITLE
Feedback | Allow for user text input to be optional

### ISSUE THREAD

**Issue by ckallemeyn** [Availity/availity-react#418]
### Current Behavior

After the user clicks the "Give Feedback" button the feedback form appears. In order to submit feedback the user must first click on a face type, (smiley, meh, frown) and then type a response into the input field before sending their feedback.

### Desired Behavior

When the user is interacting with the `FeedbackForm` allow for the user to only have to select a face type and leave the typed response as an optional field rather than requiring the user to give any written feedback.

### Suggested Solution

Add a boolean prop that controls the required attribute of the input for each of the face types. For example: 

```
     <Feedback 
        appName="Appeals"
        color="default"
        formProps={{ id: 'feedbackForm' }}
        onFeedbackSent={onFeedbackSent}
        requireUserInput={false}
     /> 
```

The "requireUserInput" prop would be passed down to the `<FeedbackForm />` component and override the required attribute of the input element. Another suggestion would be to add the "requireUserInput" prop as a FeedbackForm prop and be able to pass the an options object down to the FeedbackForm component. Here's an example: 

```
const formProps = { 
    id : 'feedbackForm' , 
    requireUserInput : false 
}
    <Feedback 
        appName="Appeals"
        color="default"
        formProps={formProps}
        onFeedbackSent={onFeedbackSent}
        requireUserInput={false}
    /> 


```

### Who does this impact? Who is this for?

This feature impacts our users directly as it allows them to not be forced into giving written feedback. Since this is an additional prop the required attribute can still be set depending on what the team/developer might want/need for their application.

### Describe alternatives you've considered

See alternative suggestion above.

### Additional context

This would be specifically for two of the Availity apps ('overpayments and appeals') so that both UIs can have identical behavior in their respective header components without reverting back to older versions. Thank you!! 😄

**Comment by GoPro16** [comment]
Thanks for submitting this feature request! 😄 

I'm not entirely sure the value that Feedback brings for us if we are only sending their essentially rating of the app they are on. We already have other surveys that run such as NPS in order to get some of these.

IIRC Feedback has had the field for user feedback as required since its existed in the react world. I am not sure if the old component your team is using is directly used from this component or custom built from the angular version.

Yes, it would be nice to allow this because then anyone, non-Availity developers can potentially have a use case. However, I don't see many people using this outside due to all of the logging and api resources that are nested inside of the component itself.

**Comment by ckallemeyn** [comment]
Thanks for getting back with me @GoPro16! 😎 

I agree with pretty much everything that you have stated above. I have found that version 1.1.2 allows for optional typed feedback. The older component was actually custom built in AngularJS, but one of our UI's (Appeals) uses the 1.3.2 version of the PageHeader React component which I believe uses the 1.1.2 version of the Feedback component.

I plan to use the v1.1.2 for my particular use case. Thanks for considering this feature request! 😄

**Comment by nylon22** [comment]
closing via #419
