### ISSUE TITLE
Field-level validation

### ISSUE THREAD

**Issue by djejaquino** [Availity/availity-react#430]
## ❓Question

Is it possible to perform [field-level validation](https://jaredpalmer.com/formik/docs/guides/validation#field-level-validation) on Availity components (i.e. `@availity/date`)?

This is important when you have dynamic validation that relies on other field values, for example.

**Comment by nylon22** [comment]
This does not look to be possible right now. We'll probably want to add a new prop: `inputProps` that gets spread onto the hidden `<Input />` rendered in `<Date />` and `<DateRange />` so that you can pass a custom `validate` prop to the input. 

- https://github.com/Availity/availity-react/blob/015266dd938867dbf23a8601df4afafc11bf9c14/packages/date/src/Date.js#L109
- https://github.com/Availity/availity-react/blob/015266dd938867dbf23a8601df4afafc11bf9c14/packages/date/src/DateRange.js#L241

**Comment by djejaquino** [comment]
We will hold on upgrading from `@availity/reactstrap-validation`, until we have this implemented.

Thanks.

**Comment by nylon22** [comment]
I'm going to reopen this so we don't lose track of it :)

**Comment by GoPro16** [comment]
Yeah I mean in the case you want to validate a field given the output of another you can always do this in a HOC that is above the 2 you are calling. 

For example (Not Exact Snippet):
```jsx
const Component = () => {
 const ctx = useFormikContext();

return(
 <div>
   <AvField name="requiredField" onChange={() => {
   ctx.validateField("dateField")
}} />
   <AvDate name="dateField" />
 </div>
)
}
```

**Comment by djejaquino** [comment]
@GoPro16 while I appreciate your input, that strategy doesn't expose Formik's `validate` function per field, allowing it to make arbitrary use of another field value. It simply triggers validation upon event; and that validation is supposed to be defined by Formik's `validationSchema`?

**Comment by djejaquino** [comment]
@nylon22 it would be cool to take a look a [this](https://github.com/Availity/availity-react/issues/428#issuecomment-574158418) too. 

A combination of Formik children `props.values` and field `validate` would do the job:

```jsx
import { Form } from '@availity/form';
import { DateField } from '@availity/date';

...

export default () => {
  return (
    <Form initialValues={{ ... }}  validationSchema={{
      // some yup schema for all fields but date2
    }}>
      { ({ values }) => {
        <DateField name="date1"/>
        <DateField name="date2" validate={value => {
         //  some logic that works with 'values.date1' and value
        } />
      }}
    </Form>
}


```

**Comment by GoPro16** [comment]
In that case, it wouldn't be hard to also just pass the `validate` prop to the `DateField` because the `useField` hook accepts the same `FieldProps` that the Formik Field does. I had tested this before on a codesandbox where I had a mix of `validationSchema` and `validate` method on the same formik field and they both were fired off which is nice.

Feel free to submit a PR if its holding you guys back otherwise I can look into adding this during some free time. We can always just add it to `DateField` for now and then add it to the other packages if you don't want to make a whole lot of changes.

**Comment by nylon22** [comment]
@djejaquino you may also want to consider using `yup.when` https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema
