### ISSUE TITLE
useAuthorize is stuck in an infinite loop

### ISSUE THREAD

**Issue by adrian-santos** [Availity/availity-react#630]
### Current Behavior

It's in an infinite loop for the permissions check and axi-user call

### Expected behavior

call the endpoint only once

### Reproducible example

https://stackblitz.com/edit/react-gwxkhe?file=src%2FApp.js

https://codesandbox.io/s/amazing-taussig-rmglq?file=/src/App.js

### Suggested solution(s)

@jordan-a-young has a fix

Brian Overbay had a note to pass it as a string, not an array

### Your environment

```bash
npx envinfo --npmPackages '@availity/*' --binaries
```

**Comment by bryanmorganoverbey** [comment]
My comment was when you pass the permissions to useAuthorize like:
`const [authorized, loading] = useAuthorize(["1234", "5678"], {
    region: "FL"
  });`
in this array format, you will get a constant reloading of the component. But when you pass the permissions as a string like:
`const [authorized, loading] = useAuthorize('["1234", "5678"]', {
    region: "FL"
  });`
it will work as expected.
So the issue seems to be how the function handles the array parameter.

**Comment by chrishavekost** [comment]
Thank you guys for opening the issue. Jordan and I looked at looked over this and will address a few things with the bug fix:

- clean up `useEffect` hook and its dependencies
- implement `react-query` for at least the `getCurrentRegion` call
- see if some of the more complex logic can be refactored/optimized
